version: '3.8'

networks:
  videogamesnet:

volumes:
  mongovideogamesdb:

services:

  #container php
  videogamesphp:
    container_name: phpvideo
    build:
      context: ./php
    ports:
      - "9000:9000"
    environment:
      TZ: UTC
      APP_PATH: "/var/www/symfo"
    volumes:
      - ./app:/var/www/symfo

    networks:
      - videogamesnet
    depends_on:
      - videogamesmongo

  #container web
  videogamesnginx:
    container_name: nginxvideo
    image: nginx:stable-alpine
    ports:
      - '80:80'
      - '442:443'
    volumes:
      - ./app:/var/www/symfo
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    environment:
      TZ: UTC
    depends_on:
      - videogamesphp
      - videogamesmongo
      - videogamesnode
    networks:
      - videogamesnet

  #container node
  videogamesnode:
    container_name: nodevideo
    build:
      context: ./node
    volumes:
      - ./app:/var/www/symfo
    environment:
      TZ: UTC
    depends_on:
      - videogamesphp
    networks:
      - videogamesnet
    tty: true

  #container mongo
  videogamesmongo:
    container_name: mongovideo
    image: mongo:latest
    ports:
      - '27018:27017'
    volumes:
      - mongovideogamesdb:/data/db
      - ./datascript:/datascript
    environment:
      TZ: UTC
      MONGODB_INITDB_ROOT_USERNAME: videoadmin
      MONGODB_INITDB_ROOT_PASSWORD: video2024
    networks:
      - videogamesnet
